apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: be
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://34.66.99.160"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  selector:
    matchLabels:
      app: gcloudtest
      tier: be
  replicas: 3
  template:
    metadata:
      labels:
        app: gcloudtest
        tier: be
    spec:
      containers:
      - name: gcloudtest-be
        image: gcr.io/deployment-test-239915/gcloud-test-be:v8
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3000
